### ISSUE TITLE
"Context" section appearing twice in a template

### ISSUE THREAD

**Issue by autra** [TalAter/open-source-templates#14]
In one of the path, you can end up with a ISSUE_TEMPLATE.md having 2 `Context` sections.

## Expected Behavior

Each section should have a different name.

## Current Behavior

After following the "adventure" I got a md file with 2 `Context` sections.

## Possible Solution

Maybe replace 

```md
## Context
<!--- Provide a more detailed introduction to the issue itself, and why you consider it to be a bug -->
```

by 

```md
## Description
<!--- Provide a more detailed introduction to the issue itself, and why you consider it to be a bug -->
```

## Steps to Reproduce
1. Visit https://www.talater.com/open-source-templates/#/page/98
2. Choose the *Issues* box
3. Choose "Focus on bugs"
4. Choose "My project run in the browser"

Thanks!

**Comment by TalAter** [comment]
Ohh my!

I just fixed it.
Thank you.
