### ISSUE TITLE
Tweet buttons on epilogues do not appear correctly in Chrome

### ISSUE THREAD

**Issue by Chris-Bitler** [TalAter/open-source-templates#17]
The tweet button at the end of the sentence in the second bullet point on the epilogue don't appear to show up for me. At first I thought it was my adblocker, but even after disabling uBlock Origin, and refreshing the page, the button still didn't appear. However, in developer tools, there is html being loaded in the iframe, and if I follow the link in the anchor tag manually it will show a tweet button.

## Expected Behavior
There should be a tweet button at the end of the second bullet point on the epilogues.

## Current Behavior
![](http://v-l.pw/imgs/0tnEAfLIofb.png)

No tweet button appears

## Possible Solution
I'm not entirely sure how to fix this, as the data is loading in the iframe, but the button appears to not appear.

## Steps to Reproduce (for bugs)
1. Go through either of the stories to the end where you see the templates
2. The tweet button will be missing from the second bullet point.

## Context
I was playing around on the site after the website was linked to me by a friend. At first I thought it could be my adblock, but upon disabling the adblock and reloading the page the button was still not there, despite there being html loaded in the iframe.

## Your Environment

* Version used: Current version on https://www.talater.com/open-source-templates/
* Browser Name and version: Chrome Version 65.0.3325.181 (Official Build) (64-bit)
* Operating System and version (desktop or mobile): Windows 10 Version 1709

**Comment by TalAter** [comment]
Thank you @Chris-Bitler for bringing this to my attention.

This seems to be due to a change in Twitter's script (they no longer render a widget that isn't visible when it is called). I added a simple link and image instead.
