### ISSUE TITLE
Templates have a few typos and grammatical errors

### ISSUE THREAD

**Issue by crd** [TalAter/open-source-templates#19]
## Current vs. Expected Behavior
This project is great and just needs a few tweaks. 

1) Project's PR template isn't consistent with those generated by the project

See [Eating your own dog food](https://en.wikipedia.org/wiki/Eating_your_own_dog_food)

```
 ## How Has This Been Tested?
 <!--- Please describe in detail how you tested your changes. -->
-<!--- Include details of your testing environment, tests ran to see how -->
-<!--- your change affects other areas of the code, etc. -->
+<!--- Include details of your testing environment, and the tests you ran to -->
+<!--- see how your change affects other areas of the code, etc. -->
```

2) 'that' instead of 'which'

The below are considered defining clauses, requiring 'that' instead of 'which'. See https://www.grammarly.com/blog/which-vs-that/

```
-- [ ] Bug fix (non-breaking change which fixes an issue)
-- [ ] New feature (non-breaking change which adds functionality)
+- [ ] Bug fix (non-breaking change that fixes an issue)
+- [ ] New feature (non-breaking change that adds functionality)
```
3) 'changes' should be capitalized in header

```
-## Types of changes
+## Types of Changes
```

**Comment by TalAter** [comment]
Thank you @crd 

I really appreciate this kind of pull request. I have been known to send PRs to projects fixing what to some might seem like trifles (e.g., authors using `i.e.` when they should have used `e.g.`). To me, these fixes are anything but trifle. More importantly they demonstrate the power of open source. Many people contributing together (each with their own skills) to continuously improve software one commit at a time.

What do you think of the commit (94d4dcbfaa641b639080d4a9ac41c26e2ef315b5) that I added to your PR?

**Comment by crd** [comment]
Hey @TalAter -- I'm good either way, I would just want the project's template and the seed material to align:

https://github.com/TalAter/open-source-templates/blame/master/site/templates/pull-requests/description/issue-required.md#L17
https://github.com/TalAter/open-source-templates/blame/master/site/templates/pull-requests/description/generic.md#L12

**Comment by TalAter** [comment]
Aligned in 658bdade68dec8932f79923eed65abff337b4e20

Thank you 🙏
